### ISSUE TITLE
Unpredictable test output - v1.5

### ISSUE THREAD

**Issue by simondib** [NimaSoroush/differencify#104]
I am at a loss to work out what's going with these test results:

![image](https://user-images.githubusercontent.com/7483506/46536145-f00ead00-c8f0-11e8-9301-43a6d71db658.png)

Test 1 should have failed
Test 2 & 3 failed as expected

Test 1 & Test 3 have test outputs are both blank (for reasons unknown), but only Test 3 has failed as expected.

I am running the test suites against a local browsersync server (Webpack/Gulp). Test pages inside the browser all appear as expected.

Any ideas?

**Comment by NimaSoroush** [comment]
Hi @simondib: Currently `differencify-jest-reporter` only looks for automatic test name generated by jest. If you have custom test name the reporter is not able to find the path for those tests. That is something need to be updated in next version of differencify-jest-reporter

**Comment by NimaSoroush** [comment]
Also when you run them, do you see that `__current_output__` folder being generated with all you snapshots in it?

Please paste your jest reporter config here as well

**Comment by simondib** [comment]
Reporter config: 

```   
 "reporters": [
      "default",
      [
        "differencify-jest-reporter",
        {
          "debug": false,
          "reportPath": "differencify_reports",
          "reportTypes": {
            "html": "index.html",
            "json": "index.json"
          }
        }
      ]
    ],
```

Current output is being generated. Sample output filename: 

`Fixture Match - Club - PREGAME appear correctly on small devices.current.png`

Generated from this test: 

```

describe('Fixture Match - Club - PREGAME', () => {
  beforeAll(async () => {
    jest.setTimeout(CONFIG.global.timeout);
  });

  afterAll(async () => {
    await differencify.close();
  });


  it('appear correctly on small devices', async () => {
    await differencify
      .init()
      .launch(CONFIG.launch)
      .newPage()

      .setViewport(getViewport('small', VIEWPORT_HEIGHT))
      .goto(TEST_HOST + PATH)
      .waitFor(4000)

      .screenshot()
      .toMatchSnapshot()
      .close()
      .end();
  });
});
```

**Comment by simondib** [comment]
@NimaSoroush could this be as simple as the current image not being properly deleted prior to the subsequent test report being generated? The failed image above is from the previous test - it shouldn't appear in a passed test.

**Comment by NimaSoroush** [comment]
Yeah. That seems to be the issue. I can put a fix for it or if you need this quick feel free to raise a PR

**Comment by NimaSoroush** [comment]
I fixed the issue here https://github.com/NimaSoroush/differencify/pull/105

v1.5.1 should be out and ready to use https://www.npmjs.com/package/differencify
