### ISSUE TITLE
Question: Does this work across browsers and devices?

### ISSUE THREAD

**Issue by danieltisdale** [NimaSoroush/differencify#106]
Hi,

I'm looking for a tool that would work across browsers and devices. Would this work for that or would it only work on Chrome?

Thanks!

**Comment by NimaSoroush** [comment]
Hi @danieltisdale

It only works with chrome. Why do you need to make it work cross devices/browsers? This is just for visual regression 

Nima

**Comment by danieltisdale** [comment]
@NimaSoroush Hi Nima,

Our platform runs across devices, browsers, OS versions, so I wanted to find a tool that would allow me to see visual regressions when we deploy a new version of the code. Essentially, we'd like to be able to see if there are any changes across Edge, Firefox, Chrome, Safari, etc from version to version of our code. Does that make sense?

**Comment by NimaSoroush** [comment]
Hi Daniel,

Yeah, that makes sense, but there is a tradeoff between what you get as a local (possibly dockerized) browser vs using a cloud provider which has a variety of browser/OS combinations and you can do what you described. 

Differencify only focuses on visual regression testing on chrome headless which can easily be integrated with CI tools and doesn't need 3rd parties to run the visual test

VS

Something like [applitools](https://applitools.com) which is a cloud visual regression provider
