### ISSUE TITLE
Unable to take particular 'Div' screenshot

### ISSUE THREAD

**Issue by voletiswaroop** [NimaSoroush/differencify#116]
I have a scenario where I have to take a screenshot the particular 'div/section' which is not happening with page.screenshot().

Thanks in Advance.

**Comment by NimaSoroush** [comment]
Hi @voletiswaroop , this is already supported scenario as Differencify supports full Puppeteer API. By Puppeteer API you can use [elementHandle.screenshot](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#elementhandlescreenshotoptions) method to take a screenshot of an element. Something like this should work,

```
(async () => {
  const target = differencify.init({ chain: false });
  await target.launch();
  const page = await target.newPage();
  await page.goto('https://www.skyscanner.net/');
  const legalInfoHandle = await page.$('.legal-info__copyright');
  const image = await legalInfoHandle.screenshot();
  const result = await target.toMatchSnapshot(image)
  await page.close();
  await target.close();
  console.log(result);
})();
```

**Comment by NimaSoroush** [comment]
Please reopen the issue if needed. Thanks

**Comment by voletiswaroop** [comment]
Thank you so much @NimaSoroush
