### ISSUE TITLE
Why are we not using Chromy.cleanup?

### ISSUE THREAD

**Issue by danrr** [NimaSoroush/differencify#17]
https://github.com/OnetapInc/chromy#static-cleanup

**Comment by NimaSoroush** [comment]
Already considered that, but not possible with differencify model. I will be happy if you have an idea of how we could use it

**Comment by NimaSoroush** [comment]
possible solution: 
- extending chromy with resize() function
- Have one instance of chromy in differencify constructor
- run chromy with resize function for every tests
- let chromy does the cleanup
