### ISSUE TITLE
Consider using puppeteer

### ISSUE THREAD

**Issue by danrr** [NimaSoroush/differencify#34]
@NimaSoroush have you considered Puppeteer? 
it has a couple cool things:
1. is from GoogleChrome org
2. https://github.com/GoogleChrome/puppeteer#default-runtime-settings >2. Runs a bundled version of Chromium

**Comment by NimaSoroush** [comment]
Yeah. This looks really cool. but `Puppeteer requires Node version 7.10 or greater` worries me

**Comment by NimaSoroush** [comment]
We could still go with this by:

1: adding backward compatibility to puppeteer
2: update our node-chrome-headless base image to use node 7.10

**Comment by danrr** [comment]
Since this is a dev dependency (and we're moving to node 8 internally soon anyway) and the image it runs on doesn't need to be deployed, I think we can make it use node 7 or 8 without issue.

Also, we don't need to use `node-chrome-headless` anymore if this comes with its own chrome, right?

**Comment by NimaSoroush** [comment]
Yeah, I don't see any problem with that.
yep. no need for node-chrome-headless. I try to put a PR for this soon
