### ISSUE TITLE
Allow options for page.goto

### ISSUE THREAD

**Issue by badsyntax** [NimaSoroush/differencify#51]
It would be useful to pass options to the puppeteer `page.goto` method from the differencify `goto` method.

A very useful option is the `waitUntil: 'networkidle'` option. 

In my particular case, it looks like chrome is not treating a `link` tag in the body as blocking so my visual test images are not being generated correctly. Using the `waitUntil: 'networkidle'` fixes this.

**Comment by NimaSoroush** [comment]
Hi Richard,

Thanks for raising this. Yeah, it makes total sense. Do you mind adding a PR for this? Should be a quick one.
@badsyntax

**Comment by ms88privat** [comment]
I like the idea of using puppeteer, image comparison and jest snapshots together. What I don't like is this custom API of differencify. We will never be up2date with puppeteer and the user has to learn again a new API. Can we not just use puppeteer and call a snapshot function wherever we want to compare some screenshots? I know it is simpler said then done. But can we try? I would love to help.

**Comment by NimaSoroush** [comment]
You are right @ms88privat and I thought a lot about this to make the API similar to puppeteer API. Although there are some issues that I am concerned about:

- Chaining over different method calls.
- Failing early in case any of steps went wrong
- Custom debugging that differencify provides
- Browser instance management that differencify does behind the scene

All of them achievable by keeping the differencify interface matching puppeteer on the fly. Just need some extra work.
I am happy to explore all I mentioned above in a separate branch and address them one by one together @ms88privat

**Comment by NimaSoroush** [comment]
I raised [this issue](https://github.com/NimaSoroush/differencify/issues/53) to follow up on matching differencify and puppeteer API.

@badsyntax: This should potentially solve your issue as well

**Comment by NimaSoroush** [comment]
Closed by [#54]
