### ISSUE TITLE
Slack channel?

### ISSUE THREAD

**Issue by ms88privat** [NimaSoroush/differencify#57]
I think it would be nice to have a way of direct communication? For example, what is the reason for this LOC: https://github.com/NimaSoroush/differencify/blob/match-puppeteer-api/src/page.js#L103 ?

**Comment by danrr** [comment]
I can answer the `functionToString` question: because the browser and test environment don't share a context so if you want to pass a parameter to a function that is executed in the browser you need to pass the function as a string with the variable baked in.

**Comment by NimaSoroush** [comment]
@ms88privat: Yeah a public channel makes sense indeed. I created a gitter channel for this project here : https://gitter.im/differencify

And for general QA: https://gitter.im/differencify/QA
I will add this to readme as well.

Yeah, as @danrr said, that is kind of string evaluation within browser context. That could be achieved by `execute('expression')` as well

**Comment by ms88privat** [comment]
Thanks, so we should remove it now with puppeteer ?

**Comment by danrr** [comment]
It's not hurting anything by being there, but it's pretty much dead code.

If you're touching it, feel free to use the proper Puppeteer API for this and remove anything that's not relevant anymore.

**Comment by NimaSoroush** [comment]
Yeah, it makes sense to be cleared out. we might still want to keep the function name just in case to not introduce breaking changes
