### ISSUE TITLE
Overflowed height breaks the chrome headless with `parameter height not set`

### ISSUE THREAD

**Issue by KamenB** [NimaSoroush/differencify#6]
If I specify a selector for screenshot capturing, and if 
```
.SHIELD-UP-HIDE-BODY-OVERFLOW {
  overflow: visible;
}
```
to my body element an error will be thrown which says:

`Error: extract_area: parameter height not set`

please fix

**Comment by NimaSoroush** [comment]
This should be resolved in version v1.0.0
