### ISSUE TITLE
Jest example needs update

### ISSUE THREAD

**Issue by hejhj** [NimaSoroush/differencify#67]
It turns out I have to add these two methods to the test so the jest test can run successfully.
       .launch()
       .newPage()
or else I'm getting error: 
: TypeError: Cannot read property 'goto' of null
          at Target._handleFunc (/Users/jayhe/Desktop/jestDemo/node_modules/differencify/dist/target.js:111:50)

The successful jest test I'm using: 
import Differencify from 'differencify';
const differencify = new Differencify({ debug: true });
describe('tests differencify', () => {
  it('validate github page appear correctly', async () => {
    await differencify
      .init()
      .launch()
      .newPage()
      .goto('https://github.com/NimaSoroush/differencify')
      .screenshot()
      .toMatchSnapshot()
      .close()
      .end();
  });
});

**Comment by NimaSoroush** [comment]
Hi @hejhj ,

Yeah, you are right. I'll update the docs.
BTW, there are integration tests for this project which using Jest to run tests. you can look at those test as example as well: https://github.com/NimaSoroush/differencify/blob/master/src/integration.tests/integration.test.js
