### ISSUE TITLE
Add support for taking screenshot of the element 

### ISSUE THREAD

**Issue by NimaSoroush** [NimaSoroush/differencify#71]
Differencify currently get screenshot of the whole page. It should support [elementHandle.screenshot](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions)

**Comment by PierrickGT** [comment]
Hi @NimaSoroush,
Has this improvement been abandoned?

**Comment by NimaSoroush** [comment]
Hi @PierrickGT , This is already doable with the current implementation in unchained mode. Something like this should do the trick for you

```
(async () => {
  const target = differencify.init({ chain: false });
  await target.launch();
  const page = await target.newPage();
  await page.goto('https://www.skyscanner.net/');
  const legalInfoHandle = await page.$('.legal-info__copyright');
  const image = await legalInfoHandle.screenshot();
  const result = await target.toMatchSnapshot(image)
  await page.close();
  await target.close();
  console.log(result);
})();
```

Let me know if that helped

**Comment by PierrickGT** [comment]
It works perfectly, thank you for the quick response and code example.

**Comment by NimaSoroush** [comment]
Good to hear that. You are welcome
