### ISSUE TITLE
Build artifacts in 1.4.0

### ISSUE THREAD

**Issue by Swingline0** [NimaSoroush/differencify#88]
@NimaSoroush It appears as though the 1.4.0 package doesn't have the latest build artifacts. Is it possible that it was published without `npm run build` occurring before hand?

Notice the differing function signatures between my build (left) and the tarball retrieved from NPM (right)

![image](https://user-images.githubusercontent.com/1479206/41769473-646c4930-75dd-11e8-829d-a492d7853b86.png)

If this was a publishing mistake and not something on my end, I would recommend configuring a [`prepare` NPM script](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) such as:

```json
  "prepare": "npm run build"
```

This will run _before_ publishing as well as after an install from Github, it ensures that no matter how the package is pulled into a project it should have freshly built artifacts.

**Comment by NimaSoroush** [comment]
Ahh, my bad. That was a publish without build. I'll fix it just now. a prepare command makes sense

**Comment by Swingline0** [comment]
Merged #89, going to close those. Thanks for the always speedy response, @NimaSoroush!

**Comment by NimaSoroush** [comment]
Thanks for raising this. Fixed!
https://www.npmjs.com/package/differencify

**Comment by Swingline0** [comment]
Can confirm, 1.4.1 works beautifully. Thanks!
